
from requests_oauthlib import OAuth1Session
import random
import json
import os
import datetime
import pytz

access_token = os.environ.get('TWITTER_ACCESS_TOKEN')
access_token_secret = os.environ.get('TWITTER_ACCESS_TOKEN_SECRET')
consumer_key = os.environ.get('TWITTER_CONSUMER_KEY')
consumer_secret = os.environ.get('TWITTER_CONSUMER_SECRET')
# Use the tokens directly if they are already available

oauth = OAuth1Session(
    consumer_key,  # consumer_key
    client_secret=consumer_secret,  # consumer_secret
    resource_owner_key=access_token,
    resource_owner_secret=access_token_secret,
)

# # List of NHL facts (you can replace this with your data source)
nhl_facts = [
    "The Stanley Cup is the oldest professional sports trophy in North America.",
    "Wayne Gretzky holds the record for the most career points in the NHL with 2,857.",
    "Bobby Orr holds the record for the highest single-season plus-minus rating at +124.",
    "The Montreal Canadiens have won the Stanley Cup 24 times, the most in NHL history.",
    "The Toronto Maple Leafs have not won a Stanley Cup since 1967, the longest current drought in the league.",
    "The 1976-77 Montreal Canadiens hold the record for the most points in a single season with 132.",
    "The Edmonton Oilers scored the most goals in a single season with 446 in 1983-84.",
    "Alex Ovechkin has led the NHL in goals scored multiple times, including eight Rocket Richard Trophy wins.",
    "Glenn Hall holds the record for most consecutive games played by a goaltender at 502.",
    "The Boston Bruins had the longest undefeated streak at home, going 29 games without a loss in 1976-77.",
    "The 1988-89 Calgary Flames won the Stanley Cup with the fewest regular-season wins (54).",
    "The NHL has had two lockouts resulting in canceled seasons, one in 2004-2005 and another in 2012-2013.",
    "Ken Dryden won the Conn Smythe Trophy as a rookie goaltender in 1971.",
    "Maurice Richard was the first player to score 50 goals in a season in 1944-45.",
    "The longest successful penalty kill in NHL history lasted 11 minutes and 7 seconds.",
    "The fastest hat trick in NHL history was scored in just 21 seconds by Bill Mosienko in 1952.",
    "Doug Harvey won the Norris Trophy as the league's best defenseman seven times.",
    "Martin Brodeur holds the record for most wins by a goaltender in a single season with 48.",
    "The Buffalo Sabres and Vancouver Canucks entered the NHL as expansion teams in 1970.",
    "The Pittsburgh Penguins won back-to-back Stanley Cups in 2016 and 2017 with Sidney Crosby as their captain.",
    "Gordie Howe had a record 22 NHL All-Star Game appearances.",
    "Bobby Hull was the first player to score more than 50 goals in a season.",
    "The 1974-75 Washington Capitals hold the record for the worst regular-season record in NHL history.",
    "The 'Bash Brothers' were Bob Probert and Joey Kocur, known for their physical play.",
    "The 'Czechmates' were Jaromir Jagr and Mario Lemieux, who formed a dynamic duo for the Penguins.",
    "The Philadelphia Flyers won back-to-back Stanley Cups in 1974 and 1975.",
    "Patrick Kane scored the Stanley Cup-winning goal in overtime in 2010.",
    "The 1970-71 Boston Bruins had a remarkable +216 goal differential.",
    "The 'Legion of Doom' line in Philadelphia featured Eric Lindros, John LeClair, and Mikael Renberg.",
    "The 'Russian Five' in Detroit included Sergei Fedorov, Igor Larionov, Slava Kozlov, Vyacheslav Fetisov, and Vladimir Konstantinov.",
    "The 'Finnish Flash' Teemu Selanne scored 76 goals as a rookie in 1992-93.",
    "The 1984-85 Edmonton Oilers are considered one of the greatest teams in NHL history.",
    "Martin Brodeur is the only goaltender with 30 or more wins in 12 consecutive seasons.",
    "The 'Russian Rocket' Pavel Bure scored 60 goals in back-to-back seasons.",
    "Wayne Gretzky holds the record for the most goals in a single season with 92 in 1981-82.",
    "The 1976-77 Montreal Canadiens had the best regular-season goal differential at +216.",
    "The 1983-84 Edmonton Oilers scored the most goals in a single season with 446.",
    "Brian Leetch is the only defenseman to win the Conn Smythe Trophy as playoff MVP without winning the Stanley Cup.",
    "Brad Park had the most assists in a single season by a defenseman with 75 in 1970-71.",
    "The 1977-78 Montreal Canadiens had the best penalty kill percentage in a season at 89.74%.",
    "Dave Schultz holds the record for the most penalty minutes in a single season with 472 in 1974-75.",
    "The 1998-99 Colorado Avalanche allowed the fewest goals against in a season with 167.",
    "Bobby Orr won the Norris Trophy as the best defenseman eight times in his career.",
    "The 1992-93 Pittsburgh Penguins scored 119 power-play goals, the most in a single season.",
    "Martin Brodeur is the all-time leader in career shutouts with 125.",
    "The 1981-82 Edmonton Oilers had the best power-play percentage in a season at 29.31%.",
    "Doug Jarvis holds the record for the most consecutive games played at 964.",
    "The 2005-06 Detroit Red Wings scored 3 shorthanded goals in a single period, a record.",
    "Terry Sawchuk recorded the most career shutouts as a goaltender with 103.",
    "The 1992-93 Pittsburgh Penguins had the most goals in a single season with 367.",
    "Pat LaFontaine scored the fastest goal in NHL history, just 6 seconds into a game in 1985.",
    "The 1993-94 New York Rangers won the Stanley Cup after a 54-year championship drought.",
    "The 2002-03 Dallas Stars allowed the fewest power-play goals in a season with 34.",
    "Brett Hull scored 86 goals in a single season of junior hockey in 1983-84.",
    "The 1995-96 Detroit Red Wings had the best regular-season winning percentage at .799.",
    "The 1979-80 Philadelphia Flyers had the most ties in a season with 24.",
    "Dominik Hasek won the Vezina Trophy as the best goaltender six times.",
    "The 1928-29 Boston Bruins recorded 77 ties in a single season.",
    "Bill Durnan was the first goaltender to win the Hart Trophy as league MVP in 1944.",
    "The 1999-00 Florida Panthers allowed the fewest power-play goals in a season with 30.",
    "Brett Hull recorded the most game-winning goals in a single season with 33 in 1990-91.",
    "The 1995-96 Detroit Red Wings scored the most power-play goals in a season with 131.",
    "Terry Sawchuk holds the record for the most career wins by a goaltender with 447.",
    "The 1991-92 Pittsburgh Penguins scored the most goals in a single season with 367.",
    "Most goals, single season including playoffs: Wayne Gretzky (1983-84), 100",
    "Most goals, single playoff series: Jari Kurri (six-game series) (1985), 12",
    "Most goals in a Stanley Cup Finals series: Babe Dye (1922, five games), 9",
    "Most goals in the Stanley Cup Finals, career: Maurice Richard, 34",
    "Most goals, 50 games from start of season: Wayne Gretzky (1981-82 and 1983-84), 61",
    "Fastest 50 goals from start of season: Wayne Gretzky (December 30, 1981), 39 games",
    "Most goals, one regular season game: Joe Malone (January 31, 1920), 7",
    "Most goals, one regular season home game: Joe Malone (January 31, 1920), 7",
    "Most goals, one regular season road game: Red Berenson (November 7, 1968), 6",
    "Most goals, one playoff game: Newsy Lalonde (March 1, 1919), Maurice Richard (March 23, 1944), Darryl Sittler (April 22, 1976), Reggie Leach (May 6, 1976), and Mario Lemieux (April 25, 1989), 5",
    "Most goals, one home playoff game: Maurice Richard (March 23, 1944), Darryl Sittler (April 22, 1976), Reggie Leach (May 6, 1976), and Mario Lemieux (April 25, 1989), 5",
    "Most goals, one road playoff game: Newsy Lalonde (March 1, 1919), 5",
    "Most goals, one period: Busher Jackson (November 20, 1934), Max Bentley (January 28, 1943), Clint Smith (March 4, 1945), Red Berenson (November 7, 1968), Wayne Gretzky (February 18, 1981), Grant Mulvey (February 3, 1982), Bryan Trottier (February 13, 1982), Tim Kerr (April 13, 1985), Al Secord (January 7, 1987), Joe Nieuwendyk (January 11, 1989), Peter Bondra (February 5, 1994), Mario Lemieux (January 26, 1997), Patrick Marleau (January 23, 2017), and Tage Thompson (December 7, 2022), 4",
    "Most goals, one playoff period: Tim Kerr (April 13, 1985) and Mario Lemieux (April 25, 1989), 4",
    "Most goals in one period during the Stanley Cup Finals: Busher Jackson (April 5, 1932), Ted Lindsay (April 5, 1955), Maurice Richard (April 6, 1957), Wayne Gretzky (May 25, 1985), Dirk Graham (June 1, 1992), and Peter Forsberg (June 6, 1996), 3",
    "Most game-winning goals in a single season: Phil Esposito (1970-71 and 1971-72) and Michel Goulet (1983-84), 16",
    "Most game-winning goals in a single playoffs season: Brad Richards (2004), 7",
    "Most game-winning goals in a playoff series: Mike Bossy (six-game series) (1983), 4",
    "Most career game-winning goals: Jaromir Jagr, 135",
    "Most career game-winning goals (playoffs): Wayne Gretzky and Brett Hull, 24",
    "Most assists regular season career: Wayne Gretzky, 1,963",
    "Most assists, one season, including playoffs: Wayne Gretzky (1985-86), 174",
    "Most assists, playoff series: Leon Draisaitl (five-game series) (2022), 15",
    "Most assists, one game: Billy Taylor (March 16, 1947) and Wayne Gretzky (February 15, 1980, December 11, 1985, and February 14, 1986), 7",
    "Most assists, one home game: Wayne Gretzky (February 15, 1980, and February 14, 1986), 7",
    "Most assists, one road game: Billy Taylor (March 16, 1947) and Wayne Gretzky (December 11, 1985), 7",
    "Most assists, one playoff game: Mikko Leinonen (April 8, 1982), and Wayne Gretzky (April 9, 1987), 6",
    "Most assists, one playoff home game: Mikko Leinonen (April 8, 1982), and Wayne Gretzky (April 9, 1987), 6",
    "Most assists, one period: Dale Hawerchuk (March 6, 1984), 5",
    "Most points regular season career: Wayne Gretzky, 2,857",
    "Most points playoff career: Wayne Gretzky, 382",
    "Most points career, including playoffs: Wayne Gretzky, 3,239",
    "Most points, one season: Wayne Gretzky (1985-86), 215",
    "Fastest 100 points from the start of a season: Wayne Gretzky (December 27, 1981), 34 games",
    "Most points, one season, including playoffs: Wayne Gretzky (1984-85), 255",
    "Most points, one playoff season: Wayne Gretzky (1985), 47",
    "Most points, one game: Darryl Sittler (February 7, 1976), 10",
    "Most points, one home game: Darryl Sittler (February 7, 1976), 10",
    "Most points, one road game: Peter Stastny and Anton Stastny, (February 22, 1981), 8",
    "Most points, one playoff game: Patrik Sundstrom (April 22, 1988) and Mario Lemieux (April 25, 1989), 8",
    "Most points, one playoff home game: Patrik Sundstrom (April 22, 1988) and Mario Lemieux (April 25, 1989), 8",
    "Most points, one period: Bryan Trottier (December 23, 1978) and Mika Zibanejad (March 17, 2021), 6",
    "Most points, one playoff series: Rick Middleton (seven-game series) (1983), 19",
    "Most points, team's first postseason: Reilly Smith (2018), 22",
    "Most points in the Finals, one series: Wayne Gretzky (1988), 13",
    "Most points in the Finals, career: Jean Beliveau, 62",
    "Best ± rating, regular season career: Larry Robinson, +722",
    "Best ± rating one season: Bobby Orr (1970-71), +124",
    "Best ± rating one game: Tom Bladon (December 11, 1977, 11-1 game against the Cleveland Barons), +10",
    "Worst ± rating, season: Bill Mikkelson (1974-75), -82",
    "Worst ± rating, regular season game: Greg Joly (March 15, 1977), -9",
    "Worst ± rating, regular season career: Bob Stewart, -257",
    "Best ± rating playoffs career: Jari Kurri, +101",
    "Best ± rating one playoff season: Wayne Gretzky (1984-85), +27",
    "Best ± rating, playoff game: Pat Stapleton and Bill White (April 25, 1971), and Brad Park (April 20, 1983), +7",
    "Worst ± rating playoffs career: Tomas Sandstrom, -45",
    "Worst ± rating one playoff season: Paul Reinhart (1982-83), -16",
    "Most power-play goals, career: Alexander Ovechkin, 299",
    "Most power-play goals, one season: Tim Kerr (1985-86), 34",
    "Most power-play goals, one season for a defenseman: Sheldon Souray (2006-07), 19",
    "Most power-play goals, career playoffs: Brett Hull, 38",
    "Most seasons: Gordie Howe (1946-47 to 1970-71; 1979-80) and Chris Chelios (1983-84 to 2009-10, except for the 2004-05 NHL lockout), 26",
    "Most playoff seasons: Chris Chelios (1983-84 to 2008-09, except for 1997-98 and the 2004-05 NHL lockout), 24",
    "Most consecutive playoff seasons: Larry Robinson (1972-73 to 1991-92) and Nicklas Lidstrom (1991-92 to 2011-12, except for the 2004-05 NHL lockout), 20",
    "Most games: Patrick Marleau, 1,779",
    "Most games, including playoffs: Mark Messier, 1,992",
    "Most playoff games: Chris Chelios, 266",
    "Most games played in a single season, not including playoffs: Jimmy Carson (1992-93) and Bob Kudelski (1993-94), 86",
    "Most consecutive games: Phil Kessel (November 3, 2009-current), 1064",
    "Most games played without playing in the playoffs (retired): Guy Charron, 734",
    "Most games played before playing in a playoff game: Ron Hainsey, 907",
    "Most games coached in the Stanley Cup Finals: Dick Irvin, 77",
    "Most games played in the Stanley Cup Finals: Red Kelly and Henri Richard, 65",
    "Most games won by a coach in the Stanley Cup Finals: Scotty Bowman, 36",
    "Most games coached by the first coach of an expansion franchise: Barry Trotz (Nashville Predators), 1,196",
    "Most Stanley Cup wins as a player: Henri Richard, 11",
    "Most Stanley Cup wins as a non-player: Scotty Bowman, 14",
    "Most Stanley Cup wins, combined player or non-player: Jean Beliveau, 17",
    "Most different teams with Stanley Cup victory, Combined player/non-player: Al Arbour, 4",
    "Most different teams with Stanley Cup victory, Non-player: Tommy Gorman and Scotty Bowman, 4",
    "Most Hart Memorial Trophies: Wayne Gretzky, 9",
    "Most consecutive Hart Memorial Trophies: Wayne Gretzky, 8",
    "Most Ted Lindsay Awards: Wayne Gretzky, 5",
    "Most consecutive Ted Lindsay Awards: Wayne Gretzky, 4",
    "Most Conn Smythe Trophies: Patrick Roy, 3",
    "Most consecutive Conn Smythe Trophies: Bernie Parent, Mario Lemieux, and Sidney Crosby, 2",
    "Most James Norris Trophies: Bobby Orr, 8",
    "Most consecutive James Norris Trophies: Bobby Orr, 8",
    "Most Maurice \"Rocket\" Richard Trophies: Alexander Ovechkin, 9",
    "Most consecutive Maurice \"Rocket\" Richard Trophies: Alexander Ovechkin, 4",
    "Most Art Ross Trophies: Wayne Gretzky, 10",
    "Most consecutive Art Ross Trophies: Wayne Gretzky, 7",
    "Most Frank J. Selke Trophies: Patrice Bergeron, 6",
    "Most consecutive Frank J. Selke Trophies: Bob Gainey, 4",
    "Most Lady Byng Trophies: Frank Boucher, 7",
    "Most consecutive Lady Byng Trophies: Frank Boucher and Pavel Datsyuk, 4",
    "Most William M. Jennings Trophies: Patrick Roy and Martin Brodeur, 5",
    "Most consecutive William M. Jennings Trophies: Patrick Roy and Brian Hayward, 3",
    "Most Vezina Trophies: Jacques Plante, 7",
    "Most consecutive Vezina Trophies: Jacques Plante, 5",
    "Most Jack Adams Awards: Pat Burns, 3",
    "Most consecutive Jack Adams Awards: Jacques Demers, 2",
    "Most career goals (regular season): Wayne Gretzky, 894",
    "Most career goals (playoffs): Wayne Gretzky, 122",
    "Most career goals (total): Wayne Gretzky, 1,016",
    "Most goals, single season: Wayne Gretzky (1981-82), 92",
    "Most goals, in single playoffs season: Reggie Leach (1976) and Jari Kurri (1985), 19",
    "From 1949-50 to present, the most points by a team was 135 by the 2022-23 Boston Bruins",
    "From 1949-50 to present, the fewest points by a team was 21 by the 1974-75 Washington Capitals",
    "From 1949-50 to present, the most wins by a team was 65 by the 2022-23 Boston Bruins",
    "From 1949-50 to present, the fewest wins by a team was 8 by the 1974-75 Washington Capitals",
    "From 1949-50 to present, the most ties by a team was 24 by the 1969-70 Philadelphia Flyers",
    "From 1949-50 to present, the fewest ties by a team was 2 by the 1992-93 San Jose Sharks",
    "From 1949-50 to present, the most shootout wins by a team was 15 by the 2007-08 Edmonton Oilers",
    "From 1949-50 to present, the most shootout losses by a team was 13 by the 2013-14 New Jersey Devils",
    "From 1949-50 to present, the most losses by a team was 71 by the 1992-93 San Jose Sharks",
    "From 1949-50 to present, the fewest losses by a team was 8 by the 1976-77 Montreal Canadiens",
    "From 1949-50 to present, the most goals for by a team was 446 by the 1983-84 Edmonton Oilers",
    "From 1949-50 to present, the fewest goals for by a team was 133 by the 1953-54 Chicago Black Hawks",
    "From 1949-50 to present, the most goals against by a team was 446 by the 1974-75 Washington Capitals",
    "From 1949-50 to present, the fewest goals against by a team was 131 by the 1953-54 Toronto Maple Leafs and 1955-56 Montreal Canadiens",
    "From 1926-27 to 1948-49, the most points by a team was 83 by the 1943-44 Montreal Canadiens",
    "From 1926-27 to 1948-49, the fewest points by a team was 12 by the 1930-31 Philadelphia Quakers",
    "From 1926-27 to 1948-49, the most wins by a team was 38 by the 1929-30 Boston Bruins, 1943-44 Montreal Canadiens, and 1944-45 Montreal Canadiens",
    "From 1926-27 to 1948-49, the fewest wins by a team was 4 by the 1930-31 Philadelphia Quakers",
    "From 1926-27 to 1948-49, the most ties by a team was 15 by the 1928-29 Montreal Canadiens and 1942-43 Chicago Black Hawks",
    "From 1926-27 to 1948-49, the fewest ties by a team was 1 by the 1929-30 Boston Bruins",
    "From 1926-27 to 1948-49, the most losses by a team was 39 by the 1943-44 New York Rangers",
    "From 1926-27 to 1948-49, the fewest losses by a team was 5 by the 1943-44 Montreal Canadiens and 1929-30 Boston Bruins",
    "From 1926-27 to 1948-49, the most goals for by a team was 234 by the 1943-44 Montreal Canadiens",
    "From 1926-27 to 1948-49, the fewest goals for by a team was 33 by the 1928-29 Chicago Black Hawks",
    "From 1926-27 to 1948-49, the most goals against by a team was 310 by the 1943-44 New York Rangers",
    "From 1926-27 to 1948-49, the fewest goals against by a team was 43 by the 1928-29 Montreal Canadiens",
    "From 1917-18 to 1925-26, the most points by a team was 52 by the 1925-26 Ottawa Senators",
    "From 1917-18 to 1925-26, the fewest points by a team was 8 by the 1919-20 Quebec Athletics",
    "From 1926-27 to 1948-49, the fewest points by a team was 12 by the 1930-31 Philadelphia Quakers",
    "From 1926-27 to 1948-49, the most wins by a team was 38, shared by the 1929-30 Boston Bruins, 1943-44 Montreal Canadiens, and 1944-45 Montreal Canadiens",
    "From 1926-27 to 1948-49, the fewest wins by a team was 4 by the 1930-31 Philadelphia Quakers",
    "From 1926-27 to 1948-49, the most ties by a team was 15, shared by the 1928-29 Montreal Canadiens and 1942-43 Chicago Black Hawks",
    "From 1926-27 to 1948-49, the fewest ties by a team was 1 by the 1929-30 Boston Bruins",
    "From 1926-27 to 1948-49, the most losses by a team was 39 by the 1943-44 New York Rangers",
    "From 1926-27 to 1948-49, the fewest losses by a team was 5, shared by the 1943-44 Montreal Canadiens and 1929-30 Boston Bruins",
    "From 1926-27 to 1948-49, the most goals for by a team was 234 by the 1943-44 Montreal Canadiens",
    "From 1926-27 to 1948-49, the fewest goals for by a team was 33 by the 1928-29 Chicago Black Hawks",
    "From 1926-27 to 1948-49, the most goals against by a team was 310 by the 1943-44 New York Rangers",
    "From 1926-27 to 1948-49, the fewest goals against by a team was 43 by the 1928-29 Montreal Canadiens",
    "From 1917-18 to 1925-26, the most points by a team was 52 by the 1925-26 Ottawa Senators",
    "From 1917-18 to 1925-26, the fewest points by a team was 8 by the 1919-20 Quebec Athletics",
    "From 1917-18 to 1925-26, the most wins by a team was 24 by the 1925-26 Ottawa Senators",
    "From 1917-18 to 1925-26, the fewest wins by a team was 4 by the 1919-20 Quebec Athletics",
    "From 1917-18 to 1925-26, the most ties by a team was 5 by the 1925-26 Montreal Maroons",
    "From 1917-18 to 1925-26, the most losses by a team was 24 by the 1924-25 Boston Bruins",
    "From 1917-18 to 1925-26, the fewest losses by a team was 5 by the 1919-20 Ottawa Senators",
    "From 1917-18 to 1925-26, the most goals for by a team was 129 by the 1919-20 Montreal Canadiens",
    "From 1917-18 to 1925-26, the fewest goals for by a team was 45 by the 1924-25 Montreal Canadiens",
    "From 1917-18 to 1925-26, the most goals against by a team was 177 by the 1919-20 Quebec Bulldogs",
    "From 1917-18 to 1925-26, the fewest goals against by a team was 42 by the 1925-26 Ottawa Senators",
    "From 1949-50 to present, the most points by a team was 135 by the 2022-23 Boston Bruins.",
    "From 1949-50 to present, the fewest points by a team was 21 by the 1974-75 Washington Capitals.",
    "From 1949-50 to present, the most wins by a team was 65 by the 2022-23 Boston Bruins.",
    "From 1949-50 to present, the fewest wins by a team was 8 by the 1974-75 Washington Capitals.",
    "From 1949-50 to present, the most ties by a team was 24 by the 1969-70 Philadelphia Flyers.",
    "From 1949-50 to present, the fewest ties by a team was 2 by the 1992-93 San Jose Sharks.",
    "From 1949-50 to present, the most shootout wins by a team was 15 by the 2007-08 Edmonton Oilers.",
    "From 1949-50 to present, the most shootout losses by a team was 13 by the 2013-14 New Jersey Devils.",
    "From 1949-50 to present, the most losses by a team was 71 by the 1992-93 San Jose Sharks.",
    "From 1949-50 to present, the fewest losses by a team was 8 by the 1976-77 Montreal Canadiens.",
    "From 1949-50 to present, the most goals for by a team was 446 by the 1983-84 Edmonton Oilers.",
    "From 1949-50 to present, the fewest goals for by a team was 133 by the 1953-54 Chicago Black Hawks.",
    "From 1949-50 to present, the most goals against by a team was 446 by the 1974-75 Washington Capitals.",
    "From 1949-50 to present, the fewest goals against by a team was 131 by the 1953-54 Toronto Maple Leafs and 1955-56 Montreal Canadiens.",
    "Greatest points percentage: .875, by the 1929-30 Boston Bruins.",
    "Lowest points percentage: .131, by the 1974-75 Washington Capitals.",
    "Greatest goal differential: +216, by the 1976-77 Montreal Canadiens.",
    "Lowest goal differential: -265, by the 1974-75 Washington Capitals.",
    "Best power play percentage in a season: 32.40%, by the 2022-23 Edmonton Oilers.",
    "Worst power play percentage in a season: 8.94%, by the 2020-21 Anaheim Ducks.",
    "Best penalty kill percentage in a season: 89.58%, by the 2011-12 New Jersey Devils.",
    "Worst penalty kill percentage in a season: 67.70%, by the 1979-80 Los Angeles Kings.",
    "Best home record: 36-2-2 by the 1975-76 Philadelphia Flyers.",
    "Worst home record: 7-28-5 by the 1974-75 Washington Capitals.",
    "Best away record: 31-7-3 by the 2005-06 Detroit Red Wings.",
    "Worst away record: 1-41-0, by the 1992-93 Ottawa Senators.",
    "Most shutout wins in a season: 22 of 44 games played (50.0%), by the 1928-29 Montreal Canadiens.",
    "Most shutout losses in a season: 20 of 44 games played (45.5%), by the 1928-29 Chicago Black Hawks.",
    "Longest playoff game: Detroit Red Wings vs Montreal Maroons on March 24, 1936.",
    "Most playoff games played (all teams): 130, during the 2020 Stanley Cup playoffs.",
    "Most home playoff games won (one season): 12, by 2002-03 New Jersey Devils.",
    "Most away playoff games won (one season): 10, by several teams.",
    "Most playoff overtime games won (one season): 10, by 1992-93 Montreal Canadiens.",
    "Most Stanley Cup-clinching overtime wins: 4, by the Montreal Canadiens.",
    "Most playoff games won by an expansion team in their inaugural season: 13, by 2017-18 Vegas Golden Knights.",
    "Most consecutive playoff games won: 14, by Pittsburgh Penguins starting on May 9, 1992.",
    "Most consecutive playoff games won in a single season: 11, by several teams.",
    "Most consecutive playoff games lost: 16, by Chicago Blackhawks from April 20, 1975 to April 8, 1980.",
    "Most playoff goals scored in a series by one team: 44, by the Edmonton Oilers during the 1985 Stanley Cup playoffs.",
    "Most playoff goals scored in a series by both teams: 69 (44 by the Edmonton Oilers and 25 by the Chicago Black Hawks).",
    "Fewest playoff goals scored in a series by one team: 1, by the Minnesota Wild against the Mighty Ducks of Anaheim.",
    "Most playoff goals scored by one team in one game: 13, by the Edmonton Oilers on April 9, 1987.",
    "Most playoff goals scored by one team in one period: 7, by the Montreal Canadiens on March 30, 1944.",
    "Longest Winning Streak Overall: 17 games, by 1992-93 Pittsburgh Penguins.",
    "Home Longest Winning Streak: 23 games, by 2011-12 Detroit Red Wings.",
    "Away Longest Winning Streak: 12 games, by 2005-06 Detroit Red Wings and 2014-15 Minnesota Wild.",
    "Overall Longest Winning Streak to Start the Season: 10 games, by 1993-94 Toronto Maple Leafs and 2006-07 Buffalo Sabres.",
    "Home Longest Winning Streak to Start the Season: 14 games, by 2022-23 Boston Bruins.",
    "Overall Longest Winning Streak to End the Season: 11 games, by 2005-06 New Jersey Devils.",
    "Overall Longest Undefeated Streak: 35 games, by 1979-80 Philadelphia Flyers (25 wins, 10 ties).",
    "Home Longest Undefeated Streak: 34 games, by 1976-77 Montreal Canadiens.",
    "Away Longest Undefeated Streak: 23 games, by 1974-75 Montreal Canadiens.",
    "Overall Longest Undefeated Streak to End the Season: 18 games, by 1992-93 Pittsburgh Penguins (17 wins, one tie).",
    "Overall Longest Points Streak to Start the Season: 24 games, by 2012-13 Chicago Blackhawks (21 wins, 3 shootout losses).",
    "Overall Longest Shootout Winning Streak: 11 games, by 2005-06 Dallas Stars.",
    "Overall Longest Shootout Losing Streak: 18 games, by 2013-14 and 2014-15 New Jersey Devils.",
    "Overall Longest Losing Streak: 18 games, by 2003-04 Pittsburgh Penguins and by 2020-21 Buffalo Sabres.",
    "Home Longest Losing Streak: 14 games, by 2003-04 Pittsburgh Penguins.",
    "Away Longest Losing Streak: 38 games, by 1992-93 Ottawa Senators.",
]
eastern = pytz.timezone('US/Eastern')
current_time = datetime.datetime.now(eastern)

if current_time.hour >= 17 or current_time.hour < 1:
    random.shuffle(nhl_facts)
    fact = nhl_facts.pop(0)

    # Prepare your tweet
    payload = {"text": fact}

    # Making the request
    response = oauth.post("https://api.twitter.com/2/tweets", json=payload)

    # Handle the response
    if response.status_code != 201:
        raise Exception(
            "Request returned an error: {} {}".format(response.status_code, response.text)
        )

    print("Response code: {}".format(response.status_code))